# Generated by Django 5.2.8 on 2025-11-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_currency_stock_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
